name: Staging Deployment

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add SSH Key
      run: |
        mkdir -p ${HOME}/.ssh
        echo "${{secrets.MISSING_SSH_KEY}}" > ${HOME}/.ssh/id_rsa
        chmod 700 ${HOME}/.ssh
        chmod 600 ${HOME}/.ssh/*
        eval `ssh-agent -s`
        ssh-add ${HOME}/.ssh/id_rsa

    - name: Sync theme directory
      run: |
        rsync -chav --delete \
        -e "ssh -p ${{secrets.MISSING_DEPLOY_PORT}} -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
        --exclude-from=.deploy_ignore \
        ./ ${{secrets.MISSING_DEPLOY_USER}}@${{secrets.MISSING_DEPLOY_HOST}}:${{secrets.DEPLOY_PATH}}

    - name: Successful deployment Slack notification
      if: success()
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: project-pfmc-internal
        payload: >-
          {
            "icon_emoji": ":shipit:",
            "username": "Happy Prime Deployment Bot",
            "attachments": [
                {
                    "author_name": "${{ github.event.sender.login }}",
                    "author_link": "${{ github.event.sender.html_url }}",
                    "author_icon": "${{ github.event.sender.avatar_url }}",
                    "color": "good",
                    "fallback": "Deployment from the develop branch to https://pcouncil.missingcolors.com complete.",
                    "pretext": "Deployment from the `develop` branch to https://pcouncil.missingcolors.com complete.",
                    "fields": [
                        {
                          "title": "Deployed revision",
                          "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}@${{ github.ref }}>",
                          "short": true
                        }
                    ],
                    "footer": "<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                }
            ]
          }

    - name: Deployment failed Slack notification
      if: failure()
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: project-pfmc-internal
        payload: >-
          {
            "icon_emoji": ":shipit:",
            "username": "Happy Prime Deployment Bot",
            "attachments": [
                {
                    "author_name": "${{ github.event.sender.login }}",
                    "author_link": "${{ github.event.sender.html_url }}",
                    "author_icon": "${{ github.event.sender.avatar_url }}",
                    "color": "#ff0000",
                    "fallback": "Deployment from the develop branch to https://pcouncil.missingcolors.com has failed.",
                    "pretext": "Deployment from the `develop` branch to https://pcouncil.missingcolors.com has failed.",
                    "fields": [
                        {
                          "title": "Deployed revision",
                          "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}@${{ github.ref }}>",
                          "short": true
                        }
                    ],
                    "footer": "<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                }
            ]
          }
