name: Release Deployment

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Fisheries server
      if: success()
      uses: HappyPrime/FTP-Deploy-Action@master
      env:
        FTP_METHOD: ftp
        FTP_PORT: 21
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: ${{ secrets.LOCAL_DIR }}
        REMOTE_DIR: ${{ secrets.REMOTE_DIR }}

    - name: Successful deployment Slack notification
      if: success()
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: project-pfmc-internal
        payload: >-
          {
            "icon_emoji": ":shipit:",
            "username": "Happy Prime Deployment Bot",
            "attachments": [
                {
                    "author_name": "${{ github.event.sender.login }}",
                    "author_link": "${{ github.event.sender.html_url }}",
                    "author_icon": "${{ github.event.sender.avatar_url }}",
                    "color": "good",
                    "fallback": "Deployment from the release branch to https://pcouncil.org complete.",
                    "pretext": "Deployment from the `release` branch to https://pcouncil.org complete.",
                    "fields": [
                        {
                          "title": "Deployed revision",
                          "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}@${{ github.ref }}>",
                          "short": true
                        }
                    ],
                    "footer": "<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                }
            ]
          }

    - name: Deployment failed Slack notification
      if: failure()
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: project-pfmc-internal
        payload: >-
          {
            "icon_emoji": ":shipit:",
            "username": "Happy Prime Deployment Bot",
            "attachments": [
                {
                    "author_name": "${{ github.event.sender.login }}",
                    "author_link": "${{ github.event.sender.html_url }}",
                    "author_icon": "${{ github.event.sender.avatar_url }}",
                    "color": "#ff0000",
                    "fallback": "Deployment from the release branch to https://pcouncil.org has failed.",
                    "pretext": "Deployment from the `release` branch to https://pcouncil.org has failed.",
                    "fields": [
                        {
                          "title": "Deployed revision",
                          "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}@${{ github.ref }}>",
                          "short": true
                        }
                    ],
                    "footer": "<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                }
            ]
          }
