name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: Deploy to Fisheries server
      if: success()
      uses: HappyPrime/FTP-Deploy-Action@master
      env:
        FTP_METHOD: ftp
        FTP_PORT: 21
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: ${{ secrets.LOCAL_DIR }}
        REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
    - name: Send deployment notification to Happy Prime Slack
      if: success()
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON: https://github.com/happyprime.png
        SLACK_CHANNE: river-deploys
        SLACK_USERNAME: Happy Prime
        SLACK_TITLE: PFMC Feature Set plugin deployment
        SLACK_MESSAGE: 'The PFMC Feature Set plugin has been deployed :rocket:'
    - name: Send error notification to Happy Prime Slack
      if: failure()
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON: https://github.com/happyprime.png
        SLACK_COLOR: '#ff0000'
        SLACK_CHANNE: river-deploys
        SLACK_USERNAME: Happy Prime
        SLACK_TITLE: PFMC Feature Set plugin deployment
        SLACK_MESSAGE: 'Deployment was not successful. :red_circle:'
